### ISSUE TITLE
Heroku - ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "users" does not exist

### ISSUE THREAD

**Issue by DeadSuperHero** [DeadSuperHero/askwise#31]
https://sentry.io/deadsuperhero/askwise/issues/332113277/

```
PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 8:                WHERE a.attrelid = '"users"'::regclass
                                          ^

  active_record/connection_adapters/postgresql/database_statements.rb:88:in `async_exec'
    result_as_array @connection.async_exec(sql)
  active_record/connection_adapters/postgresql/database_statements.rb:88:in `block in query'
    result_as_array @connection.async_exec(sql)
  active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
    connection_id:     object_id) { yield }
  active_support/notifications/instrumenter.rb:21:in `instrument'
    yield payload
  active_record/connection_adapters/abstract_adapter.rb:583:in `log'
    @instrumenter.instrument(
...
(83 additional frame(s) were not displayed)

ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 8:                WHERE a.attrelid = '"users"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
             (SELECT c.collname FROM pg_collation c, pg_type t
               WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation),
                     col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"users"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 8:                WHERE a.attrelid = '"users"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
             (SELECT c.collname FROM pg_collation c, pg_type t
               WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation),
                     col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"users"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

```

**Comment by DeadSuperHero** [comment]
Seem to have a bizarre issue with Heroku; not entirely sure why.

**Comment by DeadSuperHero** [comment]
For some reason, Heroku doesn't automatically run the initial rake db:seed / rake db:migrate?

Anyway, fixed.
